# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ">> Doogz' Dimension"
email: wdugan7@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<center><h3>Welcome to Doogz' Dimension!</h3><h5>Do you like coffee? Then you'll like this blog...</h5></center>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wdoogz.github.io" # the base hostname & protocol for your site
twitter_username: wdoogz
github_username:  wdoogz

# Build settings
markdown: kramdown
